flag_value {
  package: "com.android.systemui"
  name: "notification_throttle_hun"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "haptic_brightness_slider"
  state: ENABLED
  permission: READ_ONLY
}

flag_value {
  package: "com.android.systemui"
  name: "new_volume_panel"
  state: ENABLED
  permission: READ_ONLY
}
